version: '3.3'

services:
  api-service-deployment:
    image: freds00n/finalproject:latest
    container_name: finalproject
    ports:
      - "8051:8051"
    restart: always
#    volumes:
#      - sqlite_useritems_volume:/code/sqlitedb
#
#volumes:
#  sqlite_useritems_volume:
